name:                sicp-haskell
version:             0.1.0.0
github:              "ehigham/sicp-haskell"
license:             MIT
author:              "Edmund Higham"
maintainer:          "edhigham@gmail.com"
copyright:           "2020 Edmund Higham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ehigham/sicp-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.8
- random >= 1.1

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -g
    - -Weverything
    - -Wno-implicit-prelude
    - -Wno-safe
    - -Wno-missing-local-signatures
    - -Wno-missing-import-lists

tests:
  sicp-haskell-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -O0
    - -g
    - -W
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sicp-haskell
    - HUnit
