module Chapter1.Exercise14 (countChange) where
-- | Draw the tree illustrating the process generated by the `countChange`
-- | procedure of section 1.2.2 in making change for 11 cents. What are the
-- | orders of growth of the space and number of steps used by this process
-- | as the amount to be changed increases?

    countChange :: Int -> Int
    countChange = cc 5

    cc :: Int -> Int -> Int
    cc kinds amount = if amount == 0
        then 1
        else if (amount < 0 || kinds == 0)
            then 0
            else (cc (kinds - 1) amount) + (cc kinds (amount - firstDenomination kinds))
    
    firstDenomination :: Int -> Int
    firstDenomination kinds
        | kinds == 1 = 1
        | kinds == 2 = 5
        | kinds == 3 = 10
        | kinds == 4 = 25
        | otherwise = 50

    

